default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: '^.*\.snap$'

  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        # exclude: ^frontend/.*\.js$

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint
        entry: gitlint -c title-max-length.line-length=72 --ignore B6,B7 --msg-filename
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.0.5
    hooks:
      - id: prettier
        entry: prettier --write --config .prettierrc
        files: ^frontend/.*\.(js|jsx|html)$
