version: '3.7'

services:
  db:
    container_name: web3_database_dev
    init: true
    restart: always
    build:
      context: ./database
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - REDIS_URL=${REDIS_URL}
    links:
      - redis
    volumes:
      - database:/app/instance
      - ${PWD}/database:/app
    networks:
      - w3s_development-nw

  backend:
    container_name: web3_backend_dev
    init: true
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DEBUG=${DEBUG}
      - REDIS_URL=${REDIS_URL}
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - database:/app/instance
      - ${PWD}/backend:/app
      - ${PWD}/database/schema.sql:/app/schema.sql
    restart: always
    command: flask --app "server:create_app(config_env='server.config.development')" run --no-debugger --no-reload --host=0.0.0.0 --port=5000
    links:
      - redis
    depends_on:
      - db
    networks:
      - w3s_development-nw

  frontend:
    container_name: web3_frontend_dev
    init: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - ${PWD}/frontend:/app
    networks:
      - w3s_development-nw

  redis:
    container_name: web3_redis_dev
    hostname: redis
    restart: always
    image: redis:7.2-alpine
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379
    networks:
      - w3s_development-nw

  isession:
    container_name: web3_isession
    stdin_open: true
    tty: true
    command: ipython
    build:
      context: .
      dockerfile: ./isession/Dockerfile
    volumes:
      - ${PWD}/backend/server:/app/server
      - ${PWD}/backend/util:/app/util
      - ${PWD}/database/schema.sql:/app/schema.sql
      - ${PWD}/database:/app/database
      - ${PWD}/isession/.ipython:/app/.ipython
      - /app/.ipython/profile_default/pid
      - /app/.ipython/profile_default/security
      - database:/app/instance
    environment:
      - IPYTHONDIR=/app/.ipython
      - ENVIRONMENT=${ENVIRONMENT}
      - REDIS_URL=${REDIS_URL}
    links:
      - redis
    networks:
      - w3s_development-nw

volumes:
  database:


networks:
  w3s_development-nw:
