version: '3.7'

services:
  db:
    container_name: web3_database_prod
    build:
      context: ./database
    volumes:
      - database:/app/instance

  backend:
    container_name: web3_backend_prod
    build:
      context: ./backend
      target: prod
    environment:
      - FLASK_DEBUG=production
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - database:/app/instance
    restart: always
    depends_on:
      - db

  frontend:
    container_name: web3_frontend_prod
    build:
      context: ./frontend
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro
volumes:
  database:
  certbot_www:
  certbot_conf:
