version: "3.9"

services:
  db:
    container_name: web3_database
    build:
      context: ./database
    volumes:
      - ${PWD}/database/main.py:/app/main.py
      - database:/app/instance

  backend:
    container_name: web3_backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/backend:/app
      - database:/app/instance
    restart: always
    depends_on:
      - db
  frontend:
    container_name: web3_frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/frontend:/app
    restart: always
    depends_on:
      - backend
    links:
      - "backend"

volumes:
  database:
