version: '3.7'

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw
      - /var/log/letsencrypt/:/var/log/letsencrypt

  nginx80:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro

volumes:
  certbot_www:
  certbot_conf:
