version: '3.9'

services:
  db:
    container_name: web3_database_prod
    build:
      context: ./database
    volumes:
      - ${PWD}/database/main.py:/app/main.py
      - database:/app/instance

  nginx:
    container_name: web3_nginx_prod
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - backend
    links:
      - 'backend'
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw

  backend:
    container_name: web3_backend_prod
    build:
      context: ./backend
      target: prod
    volumes:
      # - ${PWD}/backend:/app
      - database:/app/instance
    restart: always
    depends_on:
      - db
  frontend:
    container_name: web3_frontend_prod
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ${PWD}/frontend:/app
    restart: always
    depends_on:
      - backend
    links:
      - 'backend'

  nginx-80:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/initial/:/etc/nginx/conf.d/:ro
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro

volumes:
  database:
  certbot_www:
  certbot_conf:
