version: '3.9'

services:
  db:
    container_name: web3_database_prod
    build:
      context: ./database
    volumes:
      - ${PWD}/database/main.py:/app/main.py
      - database:/app/instance

  nginx:
    container_name: web3_nginx_prod
    build:
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - backend
    links:
      - 'backend'

  backend:
    container_name: web3_backend_prod
    build:
      context: ./backend
      target: prod
    volumes:
      # - ${PWD}/backend:/app
      - database:/app/instance
    restart: always
    depends_on:
      - db
  frontend:
    container_name: web3_frontend_prod
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ${PWD}/frontend:/app
    restart: always
    depends_on:
      - backend
    links:
      - 'backend'

volumes:
  database:
