services:
  data_fetcher:
    container_name: web3_data_fetcher_prod
    init: true
    restart: always
    image: $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_DB_REPOSITORY:latest
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - REDIS_URL=${REDIS_URL}
      - COINGECKO_API_URL=${COINGECKO_API_URL}
      - COINGECKO_API_KEY=${COINGECKO_API_KEY}
      - CERTIFICATE_RENEWAL_LOG=${CERTIFICATE_RENEWAL_LOG}
    volumes:
      - database:/app/instance
      - /var/log:/var/log
    networks:
      - w3s-inner-nw

  backend:
    container_name: web3_backend_prod
    image: $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_BACKEND_REPOSITORY:latest
    environment:
      - FLASK_DEBUG=production
      - REDIS_URL=${REDIS_URL}
    env_file: ./backend/.env
    volumes:
      - database:/app/instance
    restart: always
    depends_on:
      - data_fetcher
    networks:
      - w3s-inner-nw
      - w3s-nw

  frontend:
    container_name: web3_frontend_prod
    image: $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_FRONTEND_REPOSITORY:latest
    ports:
      - 443:443
    restart: always
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl
    networks:
      - w3s-nw

  redis:
    container_name: web3_redis_prod
    hostname: redis
    restart: always
    image: redis:7.2-alpine
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379
    networks:
      - w3s-inner-nw

volumes:
  database:
  certbot_www:
  certbot_conf:

networks:
  w3s-nw:
  w3s-inner-nw:
