version: '3.7'

services:
  db:
    container_name: web3_database_prod
    init: true
    restart: always
    build:
      context: ./database
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - database:/app/instance
    networks:
      - w3s-inner-nw

  backend:
    container_name: web3_backend_prod
    build:
      context: ./backend
    environment:
      - FLASK_DEBUG=production
    env_file: ./backend/.env
    volumes:
      - database:/app/instance
      - ${PWD}/database/schema.sql:/app/schema.sql
    restart: always
    depends_on:
      - db
    networks:
      - w3s-inner-nw
      - w3s-nw

  frontend:
    container_name: web3_frontend_prod
    build:
      context: ./frontend
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - backend
    links:
      - backend
    volumes:
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro
    networks:
      - w3s-nw

  isession:
    container_name: web3_isession_production
    stdin_open: true
    tty: true
    command: ipython
    build:
      context: .
      dockerfile: ./isession/Dockerfile
    volumes:
      - ${PWD}/backend/server:/app/server
      - ${PWD}/backend/util:/app/util
      - ${PWD}/database/schema.sql:/app/schema.sql
      - ${PWD}/database:/app/database
      - ${PWD}/isession/.ipython:/app/.ipython
      - /app/.ipython/profile_default/pid
      - /app/.ipython/profile_default/security
      - database:/app/instance
    environment:
      - IPYTHONDIR=/app/.ipython
      - ENVIRONMENT=${ENVIRONMENT}
    networks:
      - w3s-nw

volumes:
  database:
  certbot_www:
  certbot_conf:


networks:
  w3s-nw:
  w3s-inner-nw:
