[tool.pytest.ini_options]
filterwarnings = [
    "ignore:.*distutils.*:DeprecationWarning",
    "ignore:.*werkzeug.*:DeprecationWarning"
    ]

[tool.flake8]
exclude = ".venv"
max-complexity = 10
max-line-length = 100

[tool.pylint]
disable = ["import-error"]
