version: '3.7'

services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_www:/var/www/certbot/:rw
      - certbot_conf:/etc/letsencrypt/:rw

  nginx-81:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/initial/:/etc/nginx/conf.d/:ro
      - certbot_www:/var/www/certbot/:ro
      - certbot_conf:/etc/nginx/ssl/:ro

volumes:
  certbot_www:
  certbot_conf:
