name: Lint and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

jobs:
  cancel-previous-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}

  lint-all:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run linter
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  backend-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Run pytest
        working-directory: backend
        run: pytest -vv
