name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  backend-test:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: development
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: ./scripts/manage --build development

      - name: Initialize database
        run: ./scripts/manage --init-db

      - name: Run pytest
        run: ./scripts/manage --tests
